"""empty message

Revision ID: 263e473d01dd
Revises: e1be2396d498
Create Date: 2026-01-21 09:50:34.099207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263e473d01dd'
down_revision = 'e1be2396d498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
