"""empty message

Revision ID: 51af2c4f4fa5
Revises: 23b54a3a624d
Create Date: 2026-01-21 10:15:46.726070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51af2c4f4fa5'
down_revision = '23b54a3a624d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_id_post_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['id_post'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_id_post_fkey', 'user', ['id_post'], ['id'])

    # ### end Alembic commands ###
